CREATE TABLE IF NOT EXISTS "usuarios" (
	"id" SERIAL,
	"nombre" VARCHAR(100) NOT NULL,
	"apellido" VARCHAR(100) NOT NULL,
	"email" VARCHAR(150) NOT NULL UNIQUE,
	"password_hash" VARCHAR(255) NOT NULL,
	"activo" BOOLEAN NOT NULL DEFAULT true,
	"ultimo_acceso" TIMESTAMP,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	"actualizado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "roles_usuario" (
	"id" SERIAL NOT NULL,
	"rol_id" INTEGER NOT NULL,
	"usuario_id" INTEGER NOT NULL,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "rol" (
	"id" SERIAL NOT NULL,
	"nombre" VARCHAR(50) NOT NULL UNIQUE,
	"descripcion" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "ubicaciones_tecnicas" (
	"id" SERIAL,
	"codigo" VARCHAR(50) NOT NULL UNIQUE,
	"nombre" VARCHAR(255) NOT NULL,
	"descripcion" TEXT,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	"actualizado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "plantas" (
	"id" SERIAL,
	"codigo" VARCHAR(50) NOT NULL UNIQUE,
	"nombre" VARCHAR(255) NOT NULL UNIQUE,
	"ubicacion_tecnica_id" INTEGER,
	"activa" BOOLEAN NOT NULL DEFAULT true,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	"actualizado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE INDEX "idx_plantas_ubicacion_tecnica"
ON "plantas" ("ubicacion_tecnica_id");

CREATE TABLE IF NOT EXISTS "lineas" (
	"id" SERIAL,
	"codigo" VARCHAR(50) NOT NULL,
	"nombre" VARCHAR(255) NOT NULL,
	"planta_id" INTEGER NOT NULL,
	"activa" BOOLEAN NOT NULL DEFAULT true,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	"actualizado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id"),
	CONSTRAINT "uq_lineas_codigo_planta" UNIQUE ("codigo", "planta_id")
);


CREATE INDEX "idx_lineas_planta"
ON "lineas" ("planta_id");

CREATE TABLE IF NOT EXISTS "equipos" (
	"id" SERIAL,
	"codigo" VARCHAR(100) NOT NULL UNIQUE,
	"nombre" VARCHAR(255) NOT NULL,
	"linea_id" INTEGER,
	"serial" VARCHAR(100),
	"marca" VARCHAR(100),
	"modelo" VARCHAR(100),
	"estado_operativo" VARCHAR(20) NOT NULL DEFAULT 'OPERATIVO',
	"observacion" TEXT,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	"actualizado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE INDEX "idx_equipos_linea"
ON "equipos" ("linea_id");
CREATE INDEX "idx_equipos_tipo_equipo"
ON "equipos" ("tipo_equipo");
CREATE INDEX "idx_equipos_estado_operativo"
ON "equipos" ("estado_operativo");

CREATE TABLE IF NOT EXISTS "tipo_equipo" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"equipo_id" INTEGER NOT NULL,
	"nombre" VARCHAR(20) NOT NULL UNIQUE,
	"descripcion" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "montacargas_detalles" (
	"id" SERIAL,
	"equipo_id" INTEGER NOT NULL UNIQUE,
	"denominacion" VARCHAR(255) NOT NULL,
	"tipo_montacarga" VARCHAR(100) NOT NULL DEFAULT 'Montacarga',
	"marca" VARCHAR(100) NOT NULL,
	"modelo" VARCHAR(100) NOT NULL,
	"identificacion_abreviada" VARCHAR(50) NOT NULL,
	"ubicacion_tecnica_texto" VARCHAR(100) NOT NULL,
	"denominacion_2" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "componentes" (
	"id" SERIAL,
	"equipo_id" INTEGER NOT NULL,
	"nombre" VARCHAR(255) NOT NULL,
	"descripcion" TEXT,
	"activo" BOOLEAN NOT NULL DEFAULT true,
	"orden_posicion" INTEGER NOT NULL DEFAULT 0,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	"actualizado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE INDEX "idx_componentes_equipo"
ON "componentes" ("equipo_id");
CREATE INDEX "idx_componentes_activo"
ON "componentes" ("activo");

CREATE TABLE IF NOT EXISTS "variables" (
	"id" SERIAL,
	"componente_id" INTEGER NOT NULL,
	"nombre" VARCHAR(255) NOT NULL,
	"tipo_evaluacion" VARCHAR(20) NOT NULL,
	"unidad" VARCHAR(20),
	"valor_minimo" NUMERIC(12,4),
	"valor_maximo" NUMERIC(12,4),
	"orden_posicion" INTEGER NOT NULL DEFAULT 0,
	"activa" BOOLEAN NOT NULL DEFAULT true,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	"actualizado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE INDEX "idx_variables_componente"
ON "variables" ("componente_id");
CREATE INDEX "idx_variables_tipo_evaluacion"
ON "variables" ("tipo_evaluacion");

CREATE TABLE IF NOT EXISTS "opciones_seleccion" (
	"id" SERIAL,
	"variable_id" INTEGER NOT NULL,
	"clave" VARCHAR(10) NOT NULL,
	"etiqueta" VARCHAR(100) NOT NULL,
	"orden_posicion" INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id"),
	CONSTRAINT "uq_opciones_variable_clave" UNIQUE ("variable_id", "clave")
);


CREATE INDEX "idx_opciones_seleccion_variable"
ON "opciones_seleccion" ("variable_id");

CREATE TABLE IF NOT EXISTS "inspecciones" (
	"id" BIGINT,
	"codigo_inspeccion" VARCHAR(100) NOT NULL UNIQUE,
	"tipo_inspeccion" VARCHAR(20) NOT NULL,
	"equipo_id" INTEGER NOT NULL,
	"elaborado_por" INTEGER NOT NULL,
	"revisado_por" INTEGER,
	"aprobado_por" INTEGER,
	"fecha_registro" TIMESTAMP NOT NULL DEFAULT NOW(),
	"fecha_sincronizacion" TIMESTAMP,
	"estado_inspeccion" VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
	"origen_datos" VARCHAR(20) NOT NULL DEFAULT 'ONLINE',
	"observaciones_generales" TEXT,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	"actualizado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE INDEX "idx_inspecciones_equipo"
ON "inspecciones" ("equipo_id");
CREATE INDEX "idx_inspecciones_elaborado_por"
ON "inspecciones" ("elaborado_por");
CREATE INDEX "idx_inspecciones_fecha_registro"
ON "inspecciones" ("fecha_registro");
CREATE INDEX "idx_inspecciones_estado"
ON "inspecciones" ("estado_inspeccion");
CREATE INDEX "idx_inspecciones_tipo"
ON "inspecciones" ("tipo_inspeccion");
CREATE INDEX "idx_inspecciones_origen"
ON "inspecciones" ("origen_datos");

CREATE TABLE IF NOT EXISTS "inspeccion_detalles" (
	"id" BIGINT,
	"inspeccion_id" BIGINT NOT NULL,
	"variable_id" INTEGER NOT NULL,
	"valor_numerico" NUMERIC(12,4),
	"valor_seleccion" VARCHAR(10),
	"observaciones" TEXT,
	"estado_componente" BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY("id")
);


CREATE INDEX "idx_inspeccion_detalles_inspeccion"
ON "inspeccion_detalles" ("inspeccion_id");
CREATE INDEX "idx_inspeccion_detalles_variable"
ON "inspeccion_detalles" ("variable_id");

CREATE TABLE IF NOT EXISTS "inspeccion_adjuntos" (
	"id" BIGINT,
	"inspeccion_id" BIGINT NOT NULL,
	"detalle_id" BIGINT,
	"ruta_archivo" VARCHAR(500) NOT NULL,
	"nombre_archivo" VARCHAR(255) NOT NULL,
	"tipo_mime" VARCHAR(100) NOT NULL,
	"tamano_bytes" BIGINT NOT NULL,
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE INDEX "idx_inspeccion_adjuntos_inspeccion"
ON "inspeccion_adjuntos" ("inspeccion_id");
CREATE INDEX "idx_inspeccion_adjuntos_detalle"
ON "inspeccion_adjuntos" ("detalle_id");

CREATE TABLE IF NOT EXISTS "auditoria_logs" (
	"id" BIGINT,
	"usuario_id" INTEGER,
	"accion" VARCHAR(100) NOT NULL,
	"tabla_afectada" VARCHAR(100) NOT NULL,
	"registro_id" BIGINT NOT NULL,
	"datos_previos" TEXT,
	"datos_nuevos" TEXT,
	"ip_origen" VARCHAR(45),
	"creado_en" TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);


CREATE INDEX "idx_auditoria_logs_usuario"
ON "auditoria_logs" ("usuario_id");
CREATE INDEX "idx_auditoria_logs_tabla_registro"
ON "auditoria_logs" ("tabla_afectada", "registro_id");
CREATE INDEX "idx_auditoria_logs_creado_en"
ON "auditoria_logs" ("creado_en");
ALTER TABLE "plantas"
ADD FOREIGN KEY("ubicacion_tecnica_id") REFERENCES "ubicaciones_tecnicas"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "lineas"
ADD FOREIGN KEY("planta_id") REFERENCES "plantas"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "equipos"
ADD FOREIGN KEY("linea_id") REFERENCES "lineas"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "montacargas_detalles"
ADD FOREIGN KEY("equipo_id") REFERENCES "equipos"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "componentes"
ADD FOREIGN KEY("equipo_id") REFERENCES "equipos"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "variables"
ADD FOREIGN KEY("componente_id") REFERENCES "componentes"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "opciones_seleccion"
ADD FOREIGN KEY("variable_id") REFERENCES "variables"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "inspecciones"
ADD FOREIGN KEY("equipo_id") REFERENCES "equipos"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "inspecciones"
ADD FOREIGN KEY("elaborado_por") REFERENCES "usuarios"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "inspecciones"
ADD FOREIGN KEY("revisado_por") REFERENCES "usuarios"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "inspecciones"
ADD FOREIGN KEY("aprobado_por") REFERENCES "usuarios"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "inspeccion_detalles"
ADD FOREIGN KEY("inspeccion_id") REFERENCES "inspecciones"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "inspeccion_detalles"
ADD FOREIGN KEY("variable_id") REFERENCES "variables"("id")
ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "inspeccion_adjuntos"
ADD FOREIGN KEY("inspeccion_id") REFERENCES "inspecciones"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "inspeccion_adjuntos"
ADD FOREIGN KEY("detalle_id") REFERENCES "inspeccion_detalles"("id")
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "auditoria_logs"
ADD FOREIGN KEY("usuario_id") REFERENCES "usuarios"("id")
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "roles_usuario"
ADD FOREIGN KEY("rol_id") REFERENCES "rol"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "roles_usuario"
ADD FOREIGN KEY("usuario_id") REFERENCES "usuarios"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "tipo_equipo"
ADD FOREIGN KEY("equipo_id") REFERENCES "equipos"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;